{{- $chartLabel := .Values.chartLabel }}
{{- if eq $chartLabel "" }}
{{- $chartLabel = (index (lookup "apps/v1" "Deployment" "cattle-system" "rancher").metadata.labels "chart") }}
{{- end }}
{{- if ne $chartLabel "" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
  jobLabel: rancher
  namespaceSelector:
    matchNames:
    - cattle-system
  selector:
    matchLabels:
      app: rancher
      chart: {{ $chartLabel }}
      release: rancher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancher-monitoring-metrics-view
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - ranchermetrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1   
kind: ClusterRoleBinding                                                                                                                       
metadata:                                                                                                                                      
  name: rancher-monitoring-operator-metrics
roleRef:                                         
  apiGroup: rbac.authorization.k8s.io          
  kind: ClusterRole                           
  name: rancher-monitoring-metrics-view
subjects:
  - kind: ServiceAccount
    name: rancher-monitoring-prometheus
    namespace: cattle-monitoring-system
{{- end }}
