debug: false

image:
  repository: rancher/rancher-csp-adapter
  tag: v1.0.0-rc1
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""

tolerations: []

# at least one csp must be enabled like below
aws:
  enabled: false
  accountNumber: ""
  roleName: ""
