url: https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.13.2/node-feature-discovery-chart-0.13.2.tgz
version: 103.0.0
# node-feature-discovery is only used as a dependency of sriov
doNotRelease: true
