url: https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-3.8.1.tgz
version: 101.0.0
doNotRelease: true
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
