url: https://github.com/longhorn/charts.git
subdirectory: charts/longhorn
commit: 476f726d7ab5d1de484e55f797a0953d99cb3b65
version: 100.2.0
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
    addCRDValidationToMainChart: true
