kind: ConfigMap
apiVersion: v1
metadata:
  name: default-clusterscanprofiles
  namespace: {{ template "cis.namespace" . }}
data:
  # Default ClusterScanProfiles per cluster provider type
  rke: |-
    <1.19.0: rke-profile-permissive-1.6
    >=1.19.0: rke-profile-permissive-1.20
  rke2: |-
    <1.19.0: rke2-cis-1.6-profile-permissive
    >=1.19.0: rke2-cis-1.20-profile-permissive
  eks: "eks-profile"
  gke: "gke-profile"
  aks: "aks-profile"
  k3s: "k3s-cis-1.20-profile-permissive"
  default: "cis-1.20-profile"
