url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.17.3.tgz
version: 100.1.1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
