url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.17.7.tgz
version: 101.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
