url: https://neuvector.github.io/neuvector-helm/core-2.4.2.tgz
version: 102.0.0
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
