url: https://neuvector.github.io/neuvector-helm/core-2.2.3.tgz
version: 101.0.0
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
