# Generate-Regsync-Config action will checkout release-v2.7 branch, run make regsync target and
# creates a pull request from rancherbot/charts or rancher/charts release-v2.7 branch with any image additions
# to regsync config file. This action is triggered whenever something is pushed into release-v2.7 branch.

name: Generate-Regsync-Config

on:
  push:
    branches:
      - "eio-regsync-testing"
  # Commented out for testing in the eio-regsync-testing branch
  # pull_request_review:
    # types: [submitted, edited]

jobs:
  build:
   # if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'release-v2.7'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Need to remove export version once rancher/charts gets the latest version 
      # of charts-build-script binary.
      - name: Generate Regsync
        run: |
          export CHARTS_BUILD_SCRIPT_VERSION=v0.4.2 
          make pull-scripts
          make regsync
   
      - name: Install Regsync
        run: |
          curl -o regsync https://github.com/regclient/regclient/releases/download/v0.4.8/regsync-linux-amd64
          chmod +x regsync

      - name: Sync Charts
        run: |
          ls
          time ./regsync check --config regsync.yaml
        env:
          REGISTRY_ENDPOINT: ${{ secrets.REGISTRY_ENDPOINT }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
