url: https://github.com/rancher/ui-plugin-operator.git
subdirectory: charts/ui-plugin-operator
commit: eaec3c599b4529f43f6e22fccc1107c4ffe332d1
version: 101.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
