url: https://github.com/rancher/ui-plugin-operator.git
subdirectory: charts/ui-plugin-operator
commit: 5844e1b86ab343bc5c64e4f325d56ea820c0e399
version: 101.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
