url: https://github.com/rancher/ui-plugin-operator.git
subdirectory: charts/ui-plugin-operator
commit: ad329e31dfecdbd754c789708d4fc1a70a6c2e53
version: 102.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
