url: https://github.com/rancher/ui-plugin-operator.git
subdirectory: charts/ui-plugin-operator
commit: c266c00f25f767fa30e28d4a59c18aefae536fd5
version: 101.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
